// src/components/vue/App.vue
<template>
	<div className="app">
    <p>Hello from Vue App: {{ JSON.stringify(data) }}</p>
		<slot />
	</div>
</template>

<script lang="ts">
import { createStore } from '../../lib/store';
import { useStore } from '@nanostores/vue';

export const appStore = createStore<Record<string, any>>('app', { foo: "bar" })

export default {
	setup() {
    const data = useStore(appStore)

		return {
      data
		};
	},
};
</script>

// src/components/react/App.tsx
import type { PropsWithChildren } from "react"
import { createStore } from "../../lib/store"
import { useStore } from "../../lib/react"

export const appStore = createStore<Record<string, any>>('app', { foo: "bar" })

export type AppProps = PropsWithChildren

export const App = ({ children }: AppProps) => {
  const storeData = useStore(appStore)

  return (
    <>
      <p>Hello from React App: {JSON.stringify(storeData)}</p>
      {children}
    </>
  )
}

export default App
